2022-06-19 14:56:23,267 INFO    MainThread:20628 [wandb_setup.py:_flush():76] Loading settings from /Users/holy_joon/.config/wandb/settings
2022-06-19 14:56:23,267 INFO    MainThread:20628 [wandb_setup.py:_flush():76] Loading settings from /Users/holy_joon/ws/Reinforcement/A3C-Atari/wandb/settings
2022-06-19 14:56:23,267 INFO    MainThread:20628 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2022-06-19 14:56:23,267 INFO    MainThread:20628 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program': 'main.py'}
2022-06-19 14:56:23,268 INFO    MainThread:20628 [wandb_init.py:_log_setup():428] Logging user logs to /Users/holy_joon/ws/Reinforcement/A3C-Atari/wandb/run-20220619_145623-31qsumo5/logs/debug.log
2022-06-19 14:56:23,268 INFO    MainThread:20628 [wandb_init.py:_log_setup():429] Logging internal logs to /Users/holy_joon/ws/Reinforcement/A3C-Atari/wandb/run-20220619_145623-31qsumo5/logs/debug-internal.log
2022-06-19 14:56:23,268 INFO    MainThread:20628 [wandb_init.py:init():462] calling init triggers
2022-06-19 14:56:23,268 INFO    MainThread:20628 [wandb_init.py:init():466] wandb.init called with sweep_config: {}
config: {'lr': 0.0001, 'gamma': 0.99, 'num_processes': 8, 'train_step': 30}
2022-06-19 14:56:23,268 INFO    MainThread:20628 [wandb_init.py:init():515] starting backend
2022-06-19 14:56:23,270 INFO    MainThread:20628 [backend.py:ensure_launched():217] starting backend process...
2022-06-19 14:56:23,270 INFO    MainThread:20628 [backend.py:ensure_launched():222] started backend process with pid: 0
2022-06-19 14:56:23,271 INFO    BackendThr:20628 [internal.py:wandb_internal():93] W&B internal server running at pid: 20628, started at: 2022-06-19 14:56:23.270756
2022-06-19 14:56:23,271 INFO    MainThread:20628 [wandb_init.py:init():525] backend started and connected
2022-06-19 14:56:23,274 INFO    MainThread:20628 [wandb_init.py:init():596] updated telemetry
2022-06-19 14:56:23,275 INFO    WriterThread:20628 [datastore.py:open_for_write():75] open: /Users/holy_joon/ws/Reinforcement/A3C-Atari/wandb/run-20220619_145623-31qsumo5/run-31qsumo5.wandb
2022-06-19 14:56:23,298 INFO    MainThread:20628 [wandb_init.py:init():628] communicating run to backend with 30 second timeout
2022-06-19 14:56:23,641 INFO    MainThread:20628 [wandb_run.py:_on_init():1924] communicating current version
2022-06-19 14:56:23,647 INFO    SenderThread:20628 [dir_watcher.py:__init__():205] watching files in: /Users/holy_joon/ws/Reinforcement/A3C-Atari/wandb/run-20220619_145623-31qsumo5/files
2022-06-19 14:56:23,648 INFO    SenderThread:20628 [sender.py:_start_run_threads():815] run started: 31qsumo5 with start time 1655618183
2022-06-19 14:56:23,649 INFO    SenderThread:20628 [sender.py:_save_file():949] saving file wandb-summary.json with policy end
2022-06-19 14:56:23,704 INFO    MainThread:20628 [internal.py:handle_exit():80] Internal process exited
2022-06-19 14:56:23,706 WARNING MsgRouterThr:20628 [router.py:message_loop():73] EOFError seen in message_loop
